language: node_js
node_js:
- '12.7.0'
script:
- npm run lint
- npm run test
deploy:
  provider: npm
  email: zinovik@gmail.com
  on:
    repo: zinovik/z-games-perudo
    branch: master
  skip_cleanup: true
  api_key:
    secure: GtIrWCGbo4WIzTAEajCgUwErcKJFZ8dS5anAzK5uaGyqaNBZdzzVSrkKTuAam7wvjDwnOqEGrIN4Nw3xJma81xEcU6oXgR8KlyOda7YorvrZ4+NXLhwuJx+ucegLVJWBzVDNxE7iT2RS1V5G/fU96QX67fXYuMV5g2eJl+Phawct4i8DsQr16ACwoFoUPDIGmjznH6GK8YyfMUfJ0NjZPwL3u+v8YAsS3P9Rabeg+kwkPxJ4q2EkqjJXtSIEQ2/umJHqB1KJ403xwcPSyvunDSbrQtbJ0mAllI1x/kLZnYEmpfs81nfVQGZ8Rd/6V7RrzSaV72vdJTYCfXDrNygSA1wynKA3HZklKUcI/LWCzXWVnzMj/YVB7frxtoobSrdEixT7lLxiN1imRdt6KksG5C+/eXcaL9MgEdO3ARK2R6IyBGdQZUlur8Pr7LX9OlFfWZ0pP+o2KXxRDx8kYGFxeGjz25FIcrUyyl9o+DXm8SN0m0MKSbcv5E9Kx9B4XlTJWrPIIM0W+WiKC/o7TjsYGLTXTMmrmOUvljvuj0JrPeWqppQv3DgaIONaDh6dNeQ2MVKORm7NXICfcsTUhYTLjpnte8REAO6sS80t7+Ifrqy92D2jSfHiEzTlWcw1p2sUBuEe/TINgvayAO8+DQlorF7NKhFb7hplvABpEQ8dtuk=
